/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QSlugRouteImport } from './routes/q.$slug'
import { Route as MSlugRouteImport } from './routes/m.$slug'
import { Route as AppWeeklyBundleRouteImport } from './routes/_app.weekly-bundle'
import { Route as AppTimetablesRouteImport } from './routes/_app.timetables'
import { Route as AppTimetableManagementRouteImport } from './routes/_app.timetable-management'
import { Route as AppTermReportRouteImport } from './routes/_app.term-report'
import { Route as AppTeachersRouteImport } from './routes/_app.teachers'
import { Route as AppSubmissionsRouteImport } from './routes/_app.submissions'
import { Route as AppSubjectsRouteImport } from './routes/_app.subjects'
import { Route as AppSubjectDashboardRouteImport } from './routes/_app.subject-dashboard'
import { Route as AppStudentsRouteImport } from './routes/_app.students'
import { Route as AppStudentSummaryRouteImport } from './routes/_app.student-summary'
import { Route as AppSeatingChartRouteImport } from './routes/_app.seating-chart'
import { Route as AppSchoolAnalyticsRouteImport } from './routes/_app.school-analytics'
import { Route as AppResourcesRouteImport } from './routes/_app.resources'
import { Route as AppQuestionBankRouteImport } from './routes/_app.question-bank'
import { Route as AppParentPortalRouteImport } from './routes/_app.parent-portal'
import { Route as AppParentManagementRouteImport } from './routes/_app.parent-management'
import { Route as AppParentAccessRouteImport } from './routes/_app.parent-access'
import { Route as AppOnlineMeetingsRouteImport } from './routes/_app.online-meetings'
import { Route as AppMyTasksRouteImport } from './routes/_app.my-tasks'
import { Route as AppMasterCalendarRouteImport } from './routes/_app.master-calendar'
import { Route as AppLessonPlansRouteImport } from './routes/_app.lesson-plans'
import { Route as AppLessonNotesRouteImport } from './routes/_app.lesson-notes'
import { Route as AppGradeGridRouteImport } from './routes/_app.grade-grid'
import { Route as AppDepartmentsRouteImport } from './routes/_app.departments'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'
import { Route as AppClassesRouteImport } from './routes/_app.classes'
import { Route as AppBulkGradingRouteImport } from './routes/_app.bulk-grading'
import { Route as AppAttendanceRouteImport } from './routes/_app.attendance'
import { Route as AppAssessmentsRouteImport } from './routes/_app.assessments'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'
import { Route as AppAiAssistantRouteImport } from './routes/_app.ai-assistant'
import { Route as AppAcademicSessionsRouteImport } from './routes/_app.academic-sessions'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QSlugRoute = QSlugRouteImport.update({
  id: '/q/$slug',
  path: '/q/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const MSlugRoute = MSlugRouteImport.update({
  id: '/m/$slug',
  path: '/m/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWeeklyBundleRoute = AppWeeklyBundleRouteImport.update({
  id: '/weekly-bundle',
  path: '/weekly-bundle',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetablesRoute = AppTimetablesRouteImport.update({
  id: '/timetables',
  path: '/timetables',
  getParentRoute: () => AppRoute,
} as any)
const AppTimetableManagementRoute = AppTimetableManagementRouteImport.update({
  id: '/timetable-management',
  path: '/timetable-management',
  getParentRoute: () => AppRoute,
} as any)
const AppTermReportRoute = AppTermReportRouteImport.update({
  id: '/term-report',
  path: '/term-report',
  getParentRoute: () => AppRoute,
} as any)
const AppTeachersRoute = AppTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => AppRoute,
} as any)
const AppSubmissionsRoute = AppSubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectsRoute = AppSubjectsRouteImport.update({
  id: '/subjects',
  path: '/subjects',
  getParentRoute: () => AppRoute,
} as any)
const AppSubjectDashboardRoute = AppSubjectDashboardRouteImport.update({
  id: '/subject-dashboard',
  path: '/subject-dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentsRoute = AppStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => AppRoute,
} as any)
const AppStudentSummaryRoute = AppStudentSummaryRouteImport.update({
  id: '/student-summary',
  path: '/student-summary',
  getParentRoute: () => AppRoute,
} as any)
const AppSeatingChartRoute = AppSeatingChartRouteImport.update({
  id: '/seating-chart',
  path: '/seating-chart',
  getParentRoute: () => AppRoute,
} as any)
const AppSchoolAnalyticsRoute = AppSchoolAnalyticsRouteImport.update({
  id: '/school-analytics',
  path: '/school-analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppResourcesRoute = AppResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => AppRoute,
} as any)
const AppQuestionBankRoute = AppQuestionBankRouteImport.update({
  id: '/question-bank',
  path: '/question-bank',
  getParentRoute: () => AppRoute,
} as any)
const AppParentPortalRoute = AppParentPortalRouteImport.update({
  id: '/parent-portal',
  path: '/parent-portal',
  getParentRoute: () => AppRoute,
} as any)
const AppParentManagementRoute = AppParentManagementRouteImport.update({
  id: '/parent-management',
  path: '/parent-management',
  getParentRoute: () => AppRoute,
} as any)
const AppParentAccessRoute = AppParentAccessRouteImport.update({
  id: '/parent-access',
  path: '/parent-access',
  getParentRoute: () => AppRoute,
} as any)
const AppOnlineMeetingsRoute = AppOnlineMeetingsRouteImport.update({
  id: '/online-meetings',
  path: '/online-meetings',
  getParentRoute: () => AppRoute,
} as any)
const AppMyTasksRoute = AppMyTasksRouteImport.update({
  id: '/my-tasks',
  path: '/my-tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppMasterCalendarRoute = AppMasterCalendarRouteImport.update({
  id: '/master-calendar',
  path: '/master-calendar',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonPlansRoute = AppLessonPlansRouteImport.update({
  id: '/lesson-plans',
  path: '/lesson-plans',
  getParentRoute: () => AppRoute,
} as any)
const AppLessonNotesRoute = AppLessonNotesRouteImport.update({
  id: '/lesson-notes',
  path: '/lesson-notes',
  getParentRoute: () => AppRoute,
} as any)
const AppGradeGridRoute = AppGradeGridRouteImport.update({
  id: '/grade-grid',
  path: '/grade-grid',
  getParentRoute: () => AppRoute,
} as any)
const AppDepartmentsRoute = AppDepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppClassesRoute = AppClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AppRoute,
} as any)
const AppBulkGradingRoute = AppBulkGradingRouteImport.update({
  id: '/bulk-grading',
  path: '/bulk-grading',
  getParentRoute: () => AppRoute,
} as any)
const AppAttendanceRoute = AppAttendanceRouteImport.update({
  id: '/attendance',
  path: '/attendance',
  getParentRoute: () => AppRoute,
} as any)
const AppAssessmentsRoute = AppAssessmentsRouteImport.update({
  id: '/assessments',
  path: '/assessments',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppAiAssistantRoute = AppAiAssistantRouteImport.update({
  id: '/ai-assistant',
  path: '/ai-assistant',
  getParentRoute: () => AppRoute,
} as any)
const AppAcademicSessionsRoute = AppAcademicSessionsRouteImport.update({
  id: '/academic-sessions',
  path: '/academic-sessions',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academic-sessions': typeof AppAcademicSessionsRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assessments': typeof AppAssessmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/bulk-grading': typeof AppBulkGradingRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/grade-grid': typeof AppGradeGridRoute
  '/lesson-notes': typeof AppLessonNotesRoute
  '/lesson-plans': typeof AppLessonPlansRoute
  '/master-calendar': typeof AppMasterCalendarRoute
  '/my-tasks': typeof AppMyTasksRoute
  '/online-meetings': typeof AppOnlineMeetingsRoute
  '/parent-access': typeof AppParentAccessRoute
  '/parent-management': typeof AppParentManagementRoute
  '/parent-portal': typeof AppParentPortalRoute
  '/question-bank': typeof AppQuestionBankRoute
  '/resources': typeof AppResourcesRoute
  '/school-analytics': typeof AppSchoolAnalyticsRoute
  '/seating-chart': typeof AppSeatingChartRoute
  '/student-summary': typeof AppStudentSummaryRoute
  '/students': typeof AppStudentsRoute
  '/subject-dashboard': typeof AppSubjectDashboardRoute
  '/subjects': typeof AppSubjectsRoute
  '/submissions': typeof AppSubmissionsRoute
  '/teachers': typeof AppTeachersRoute
  '/term-report': typeof AppTermReportRoute
  '/timetable-management': typeof AppTimetableManagementRoute
  '/timetables': typeof AppTimetablesRoute
  '/weekly-bundle': typeof AppWeeklyBundleRoute
  '/m/$slug': typeof MSlugRoute
  '/q/$slug': typeof QSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academic-sessions': typeof AppAcademicSessionsRoute
  '/ai-assistant': typeof AppAiAssistantRoute
  '/analytics': typeof AppAnalyticsRoute
  '/assessments': typeof AppAssessmentsRoute
  '/attendance': typeof AppAttendanceRoute
  '/bulk-grading': typeof AppBulkGradingRoute
  '/classes': typeof AppClassesRoute
  '/dashboard': typeof AppDashboardRoute
  '/departments': typeof AppDepartmentsRoute
  '/grade-grid': typeof AppGradeGridRoute
  '/lesson-notes': typeof AppLessonNotesRoute
  '/lesson-plans': typeof AppLessonPlansRoute
  '/master-calendar': typeof AppMasterCalendarRoute
  '/my-tasks': typeof AppMyTasksRoute
  '/online-meetings': typeof AppOnlineMeetingsRoute
  '/parent-access': typeof AppParentAccessRoute
  '/parent-management': typeof AppParentManagementRoute
  '/parent-portal': typeof AppParentPortalRoute
  '/question-bank': typeof AppQuestionBankRoute
  '/resources': typeof AppResourcesRoute
  '/school-analytics': typeof AppSchoolAnalyticsRoute
  '/seating-chart': typeof AppSeatingChartRoute
  '/student-summary': typeof AppStudentSummaryRoute
  '/students': typeof AppStudentsRoute
  '/subject-dashboard': typeof AppSubjectDashboardRoute
  '/subjects': typeof AppSubjectsRoute
  '/submissions': typeof AppSubmissionsRoute
  '/teachers': typeof AppTeachersRoute
  '/term-report': typeof AppTermReportRoute
  '/timetable-management': typeof AppTimetableManagementRoute
  '/timetables': typeof AppTimetablesRoute
  '/weekly-bundle': typeof AppWeeklyBundleRoute
  '/m/$slug': typeof MSlugRoute
  '/q/$slug': typeof QSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/academic-sessions': typeof AppAcademicSessionsRoute
  '/_app/ai-assistant': typeof AppAiAssistantRoute
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/assessments': typeof AppAssessmentsRoute
  '/_app/attendance': typeof AppAttendanceRoute
  '/_app/bulk-grading': typeof AppBulkGradingRoute
  '/_app/classes': typeof AppClassesRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/departments': typeof AppDepartmentsRoute
  '/_app/grade-grid': typeof AppGradeGridRoute
  '/_app/lesson-notes': typeof AppLessonNotesRoute
  '/_app/lesson-plans': typeof AppLessonPlansRoute
  '/_app/master-calendar': typeof AppMasterCalendarRoute
  '/_app/my-tasks': typeof AppMyTasksRoute
  '/_app/online-meetings': typeof AppOnlineMeetingsRoute
  '/_app/parent-access': typeof AppParentAccessRoute
  '/_app/parent-management': typeof AppParentManagementRoute
  '/_app/parent-portal': typeof AppParentPortalRoute
  '/_app/question-bank': typeof AppQuestionBankRoute
  '/_app/resources': typeof AppResourcesRoute
  '/_app/school-analytics': typeof AppSchoolAnalyticsRoute
  '/_app/seating-chart': typeof AppSeatingChartRoute
  '/_app/student-summary': typeof AppStudentSummaryRoute
  '/_app/students': typeof AppStudentsRoute
  '/_app/subject-dashboard': typeof AppSubjectDashboardRoute
  '/_app/subjects': typeof AppSubjectsRoute
  '/_app/submissions': typeof AppSubmissionsRoute
  '/_app/teachers': typeof AppTeachersRoute
  '/_app/term-report': typeof AppTermReportRoute
  '/_app/timetable-management': typeof AppTimetableManagementRoute
  '/_app/timetables': typeof AppTimetablesRoute
  '/_app/weekly-bundle': typeof AppWeeklyBundleRoute
  '/m/$slug': typeof MSlugRoute
  '/q/$slug': typeof QSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academic-sessions'
    | '/ai-assistant'
    | '/analytics'
    | '/assessments'
    | '/attendance'
    | '/bulk-grading'
    | '/classes'
    | '/dashboard'
    | '/departments'
    | '/grade-grid'
    | '/lesson-notes'
    | '/lesson-plans'
    | '/master-calendar'
    | '/my-tasks'
    | '/online-meetings'
    | '/parent-access'
    | '/parent-management'
    | '/parent-portal'
    | '/question-bank'
    | '/resources'
    | '/school-analytics'
    | '/seating-chart'
    | '/student-summary'
    | '/students'
    | '/subject-dashboard'
    | '/subjects'
    | '/submissions'
    | '/teachers'
    | '/term-report'
    | '/timetable-management'
    | '/timetables'
    | '/weekly-bundle'
    | '/m/$slug'
    | '/q/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academic-sessions'
    | '/ai-assistant'
    | '/analytics'
    | '/assessments'
    | '/attendance'
    | '/bulk-grading'
    | '/classes'
    | '/dashboard'
    | '/departments'
    | '/grade-grid'
    | '/lesson-notes'
    | '/lesson-plans'
    | '/master-calendar'
    | '/my-tasks'
    | '/online-meetings'
    | '/parent-access'
    | '/parent-management'
    | '/parent-portal'
    | '/question-bank'
    | '/resources'
    | '/school-analytics'
    | '/seating-chart'
    | '/student-summary'
    | '/students'
    | '/subject-dashboard'
    | '/subjects'
    | '/submissions'
    | '/teachers'
    | '/term-report'
    | '/timetable-management'
    | '/timetables'
    | '/weekly-bundle'
    | '/m/$slug'
    | '/q/$slug'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/academic-sessions'
    | '/_app/ai-assistant'
    | '/_app/analytics'
    | '/_app/assessments'
    | '/_app/attendance'
    | '/_app/bulk-grading'
    | '/_app/classes'
    | '/_app/dashboard'
    | '/_app/departments'
    | '/_app/grade-grid'
    | '/_app/lesson-notes'
    | '/_app/lesson-plans'
    | '/_app/master-calendar'
    | '/_app/my-tasks'
    | '/_app/online-meetings'
    | '/_app/parent-access'
    | '/_app/parent-management'
    | '/_app/parent-portal'
    | '/_app/question-bank'
    | '/_app/resources'
    | '/_app/school-analytics'
    | '/_app/seating-chart'
    | '/_app/student-summary'
    | '/_app/students'
    | '/_app/subject-dashboard'
    | '/_app/subjects'
    | '/_app/submissions'
    | '/_app/teachers'
    | '/_app/term-report'
    | '/_app/timetable-management'
    | '/_app/timetables'
    | '/_app/weekly-bundle'
    | '/m/$slug'
    | '/q/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  MSlugRoute: typeof MSlugRoute
  QSlugRoute: typeof QSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$slug': {
      id: '/q/$slug'
      path: '/q/$slug'
      fullPath: '/q/$slug'
      preLoaderRoute: typeof QSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/m/$slug': {
      id: '/m/$slug'
      path: '/m/$slug'
      fullPath: '/m/$slug'
      preLoaderRoute: typeof MSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/weekly-bundle': {
      id: '/_app/weekly-bundle'
      path: '/weekly-bundle'
      fullPath: '/weekly-bundle'
      preLoaderRoute: typeof AppWeeklyBundleRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetables': {
      id: '/_app/timetables'
      path: '/timetables'
      fullPath: '/timetables'
      preLoaderRoute: typeof AppTimetablesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timetable-management': {
      id: '/_app/timetable-management'
      path: '/timetable-management'
      fullPath: '/timetable-management'
      preLoaderRoute: typeof AppTimetableManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/term-report': {
      id: '/_app/term-report'
      path: '/term-report'
      fullPath: '/term-report'
      preLoaderRoute: typeof AppTermReportRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/teachers': {
      id: '/_app/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof AppTeachersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/submissions': {
      id: '/_app/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AppSubmissionsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subjects': {
      id: '/_app/subjects'
      path: '/subjects'
      fullPath: '/subjects'
      preLoaderRoute: typeof AppSubjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/subject-dashboard': {
      id: '/_app/subject-dashboard'
      path: '/subject-dashboard'
      fullPath: '/subject-dashboard'
      preLoaderRoute: typeof AppSubjectDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/students': {
      id: '/_app/students'
      path: '/students'
      fullPath: '/students'
      preLoaderRoute: typeof AppStudentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/student-summary': {
      id: '/_app/student-summary'
      path: '/student-summary'
      fullPath: '/student-summary'
      preLoaderRoute: typeof AppStudentSummaryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/seating-chart': {
      id: '/_app/seating-chart'
      path: '/seating-chart'
      fullPath: '/seating-chart'
      preLoaderRoute: typeof AppSeatingChartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/school-analytics': {
      id: '/_app/school-analytics'
      path: '/school-analytics'
      fullPath: '/school-analytics'
      preLoaderRoute: typeof AppSchoolAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/resources': {
      id: '/_app/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof AppResourcesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/question-bank': {
      id: '/_app/question-bank'
      path: '/question-bank'
      fullPath: '/question-bank'
      preLoaderRoute: typeof AppQuestionBankRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent-portal': {
      id: '/_app/parent-portal'
      path: '/parent-portal'
      fullPath: '/parent-portal'
      preLoaderRoute: typeof AppParentPortalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent-management': {
      id: '/_app/parent-management'
      path: '/parent-management'
      fullPath: '/parent-management'
      preLoaderRoute: typeof AppParentManagementRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/parent-access': {
      id: '/_app/parent-access'
      path: '/parent-access'
      fullPath: '/parent-access'
      preLoaderRoute: typeof AppParentAccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/online-meetings': {
      id: '/_app/online-meetings'
      path: '/online-meetings'
      fullPath: '/online-meetings'
      preLoaderRoute: typeof AppOnlineMeetingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/my-tasks': {
      id: '/_app/my-tasks'
      path: '/my-tasks'
      fullPath: '/my-tasks'
      preLoaderRoute: typeof AppMyTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/master-calendar': {
      id: '/_app/master-calendar'
      path: '/master-calendar'
      fullPath: '/master-calendar'
      preLoaderRoute: typeof AppMasterCalendarRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lesson-plans': {
      id: '/_app/lesson-plans'
      path: '/lesson-plans'
      fullPath: '/lesson-plans'
      preLoaderRoute: typeof AppLessonPlansRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/lesson-notes': {
      id: '/_app/lesson-notes'
      path: '/lesson-notes'
      fullPath: '/lesson-notes'
      preLoaderRoute: typeof AppLessonNotesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/grade-grid': {
      id: '/_app/grade-grid'
      path: '/grade-grid'
      fullPath: '/grade-grid'
      preLoaderRoute: typeof AppGradeGridRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/departments': {
      id: '/_app/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof AppDepartmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/classes': {
      id: '/_app/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AppClassesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bulk-grading': {
      id: '/_app/bulk-grading'
      path: '/bulk-grading'
      fullPath: '/bulk-grading'
      preLoaderRoute: typeof AppBulkGradingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/attendance': {
      id: '/_app/attendance'
      path: '/attendance'
      fullPath: '/attendance'
      preLoaderRoute: typeof AppAttendanceRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/assessments': {
      id: '/_app/assessments'
      path: '/assessments'
      fullPath: '/assessments'
      preLoaderRoute: typeof AppAssessmentsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ai-assistant': {
      id: '/_app/ai-assistant'
      path: '/ai-assistant'
      fullPath: '/ai-assistant'
      preLoaderRoute: typeof AppAiAssistantRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/academic-sessions': {
      id: '/_app/academic-sessions'
      path: '/academic-sessions'
      fullPath: '/academic-sessions'
      preLoaderRoute: typeof AppAcademicSessionsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAcademicSessionsRoute: typeof AppAcademicSessionsRoute
  AppAiAssistantRoute: typeof AppAiAssistantRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppAssessmentsRoute: typeof AppAssessmentsRoute
  AppAttendanceRoute: typeof AppAttendanceRoute
  AppBulkGradingRoute: typeof AppBulkGradingRoute
  AppClassesRoute: typeof AppClassesRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppDepartmentsRoute: typeof AppDepartmentsRoute
  AppGradeGridRoute: typeof AppGradeGridRoute
  AppLessonNotesRoute: typeof AppLessonNotesRoute
  AppLessonPlansRoute: typeof AppLessonPlansRoute
  AppMasterCalendarRoute: typeof AppMasterCalendarRoute
  AppMyTasksRoute: typeof AppMyTasksRoute
  AppOnlineMeetingsRoute: typeof AppOnlineMeetingsRoute
  AppParentAccessRoute: typeof AppParentAccessRoute
  AppParentManagementRoute: typeof AppParentManagementRoute
  AppParentPortalRoute: typeof AppParentPortalRoute
  AppQuestionBankRoute: typeof AppQuestionBankRoute
  AppResourcesRoute: typeof AppResourcesRoute
  AppSchoolAnalyticsRoute: typeof AppSchoolAnalyticsRoute
  AppSeatingChartRoute: typeof AppSeatingChartRoute
  AppStudentSummaryRoute: typeof AppStudentSummaryRoute
  AppStudentsRoute: typeof AppStudentsRoute
  AppSubjectDashboardRoute: typeof AppSubjectDashboardRoute
  AppSubjectsRoute: typeof AppSubjectsRoute
  AppSubmissionsRoute: typeof AppSubmissionsRoute
  AppTeachersRoute: typeof AppTeachersRoute
  AppTermReportRoute: typeof AppTermReportRoute
  AppTimetableManagementRoute: typeof AppTimetableManagementRoute
  AppTimetablesRoute: typeof AppTimetablesRoute
  AppWeeklyBundleRoute: typeof AppWeeklyBundleRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAcademicSessionsRoute: AppAcademicSessionsRoute,
  AppAiAssistantRoute: AppAiAssistantRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppAssessmentsRoute: AppAssessmentsRoute,
  AppAttendanceRoute: AppAttendanceRoute,
  AppBulkGradingRoute: AppBulkGradingRoute,
  AppClassesRoute: AppClassesRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppDepartmentsRoute: AppDepartmentsRoute,
  AppGradeGridRoute: AppGradeGridRoute,
  AppLessonNotesRoute: AppLessonNotesRoute,
  AppLessonPlansRoute: AppLessonPlansRoute,
  AppMasterCalendarRoute: AppMasterCalendarRoute,
  AppMyTasksRoute: AppMyTasksRoute,
  AppOnlineMeetingsRoute: AppOnlineMeetingsRoute,
  AppParentAccessRoute: AppParentAccessRoute,
  AppParentManagementRoute: AppParentManagementRoute,
  AppParentPortalRoute: AppParentPortalRoute,
  AppQuestionBankRoute: AppQuestionBankRoute,
  AppResourcesRoute: AppResourcesRoute,
  AppSchoolAnalyticsRoute: AppSchoolAnalyticsRoute,
  AppSeatingChartRoute: AppSeatingChartRoute,
  AppStudentSummaryRoute: AppStudentSummaryRoute,
  AppStudentsRoute: AppStudentsRoute,
  AppSubjectDashboardRoute: AppSubjectDashboardRoute,
  AppSubjectsRoute: AppSubjectsRoute,
  AppSubmissionsRoute: AppSubmissionsRoute,
  AppTeachersRoute: AppTeachersRoute,
  AppTermReportRoute: AppTermReportRoute,
  AppTimetableManagementRoute: AppTimetableManagementRoute,
  AppTimetablesRoute: AppTimetablesRoute,
  AppWeeklyBundleRoute: AppWeeklyBundleRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  MSlugRoute: MSlugRoute,
  QSlugRoute: QSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
